//% this code generated by Ai "github cobilot" ^-^
class config_agent;
    // Virtual interface
    virtual config_space_if vif;

    // Mailboxes for communication
    mailbox #(config_transaction) mb_mon_scr;
    mailbox #(config_transaction) mb_drv_gen;

    // Agent Components
    config_driver cfg_drv;
    config_monitor cfg_mon;

    // Events to signal when driving and monitoring are done
    event driverDone;

    // Constructor
    function new(
        virtual config_space_if vif, 
        mailbox #(config_transaction) mb_mon_scr,
        mailbox #(config_transaction) mb_drv_gen, 
        event driverDone
    );
        this.vif = vif;
        this.mb_mon_scr = mb_mon_scr;
        this.mb_drv_gen = mb_drv_gen;
        this.driverDone = driverDone;
        // Initialize agent components
        cfg_drv = new( mb_drv_gen,vif,driverDone);
        cfg_mon = new(vif, mb_mon_scr);
    endfunction
    
    // Main task that runs the agent components
    task run();
        fork
            cfg_drv.run();
            cfg_mon.run();
        join
    endtask



endclass // config_agent