//% this code generated by Ai "github cobilot" ^-^
class up_transport_agent;

    // Virtual interface
    virtual upper_layer_if vif;

    // Mailboxes for communication
    mailbox #(upper_layer_tr) mb_mon_scr;
    mailbox #(upper_layer_tr) mb_drv_gen;

    // Agent Components
    up_transport_driver up_drv;
    up_transport_monitor up_mon;

    // Event to signal when driving is done
    event driveDone;

    // Constructor
    function new(
        virtual upper_layer_if vif, 
        mailbox #(upper_layer_tr) mb_mon_scr,
        mailbox #(upper_layer_tr) mb_drv_gen, 
        event driveDone
    );
        this.vif = vif;
        this.mb_mon_scr = mb_mon_scr;
        this.mb_drv_gen = mb_drv_gen;
        this.driveDone = driveDone;

        // Initialize agent components
        up_drv   = new(vif, mb_drv_gen, driveDone);
        up_mon = new(vif, mb_mon_scr);
    endfunction

    // Main task that runs the agent components
    task run(input GEN speed);
        fork
            up_drv.run(speed);
            up_mon.run(speed);
        join
    endtask


endclass // ub_agent