//% this code generated by Ai "github cobilot" ^-^

class up_transport_monitor;

        virtual upper_layer_if vif;
        upper_layer_tr tr;
        mailbox #(upper_layer_tr) mb_mon_scr;

        ///////// Constructor \\\\\\\\\\
        function new(virtual upper_layer_if vif, mailbox #(upper_layer_tr) mb_mon_scr);
            this.vif = vif;
            this.mb_mon_scr = mb_mon_scr;
        endfunction
    

        ///////// Main Task \\\\\\\\\\
        task run(input GEN speed);

            while(vif.enable_receive==1) begin    
                wait_for_negedge(speed);

                wait (vif.transport_data_flag == 1'b1); // wait for the transport layer to send data
                        tr = new; 
                        tr.T_Data = vif.transport_layer_data_out; 
                        mb_mon_scr.put(tr); 
                        $display("[UPPER MONITOR ]data recieved on transport : %0d", tr.T_Data);
                
        end

        endtask

        

                // Task to wait for the negative edge of a specific clock
        task wait_for_negedge( input GEN gen_speed );
        case (gen_speed)
        gen2: @(negedge  vif.gen2_fsm_clk );
        gen3: @(negedge  vif.gen3_fsm_clk);
        gen4: @(negedge  vif.gen4_fsm_clk);
        default: @(negedge  vif.gen4_fsm_clk );
        
        endcase
        endtask
endclass