//% this code generated by Ai "github cobilot" ^-^
class up_transport_scoreboard;
  mailbox  #(upper_layer_tr) UL_mod_scr;
  mailbox #(upper_layer_tr) UL_mon_scr;

  upper_layer_tr mod_tr, mon_tr; 

  function new(mailbox #(upper_layer_tr) UL_mod_scr, mailbox #(upper_layer_tr) UL_mon_scr);
    this.UL_mod_scr = UL_mod_scr;
    this.UL_mon_scr = UL_mon_scr;
    mod_tr = new();
    mon_tr = new();

  endfunction: new

  task run_scr();

    forever begin
      // Get transactions from both mailboxes
      UL_mod_scr.get(mod_tr);
      $display("\n[Scoreboard Upper layer From Model] at time (%t) is --> %p", $time, mod_tr.convert2string());
      
      UL_mon_scr.get(mon_tr);
      $display("\n[Scoreboard Upper layer From Dut ]at time (%t) --> %p", $time, mon_tr.convert2string());
      
      //* we campare here first the data from lane 0 then lane 1
      
         // Assertion to compare the values from the two mailboxes
      assert (mod_tr.T_Data == mon_tr.T_Data) else $display("Values from the two mailboxes do not match");

        


    end
  endtask: run_scr


  
endclass